name: use remote authenticated workflow

on:
  workflow_dispatch:

jobs:
  generate:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set OIDC token
        run: |
          export OIDC=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=akita" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
          echo "TOKEN=$OIDC" >> $GITHUB_ENV
          
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'cicd-template',
              workflow_id: 'github-workflow-test.yaml',
              ref: 'main',
            })
